package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class MyTool {
    
    // @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    // private UserRepository userRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OtherClass otherClass;
    
    public void run() {
        System.out.println("Called hello and got: " + otherClass.hello());
        /*
        userRepository.findAll().forEach(n -> {
                System.out.println("User: " + n.getName());
            });
        */
    }
}
